# Generated by Django 3.2.25 on 2025-04-17 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("en-route", "En-route"),
                            ("pickup", "Pick-up"),
                            ("dropoff", "Drop-off"),
                        ],
                        default="pickup",
                        max_length=255,
                    ),
                ),
                ("pickup_latitude", models.FloatField(blank=True, null=True)),
                ("pickup_longitude", models.FloatField(blank=True, null=True)),
                ("dropoff_latitude", models.FloatField(blank=True, null=True)),
                ("dropoff_longitude", models.FloatField(blank=True, null=True)),
                ("pickup_time", models.DateTimeField(blank=True, null=True)),
                (
                    "id_driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rider_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
