# Generated by Django 3.2.25 on 2025-04-17 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_ride"),
    ]

    operations = [
        migrations.CreateModel(
            name="RideEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id_ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.ride"
                    ),
                ),
            ],
        ),
    ]
